### ISSUE TITLE
Not work on Android 11

### ISSUE THREAD

**Issue by igormenin** [danieloquelis/flutter_device_identifier#1]
`E/flutter ( 5805): Caused by: android.os.RemoteException: Remote stack trace:
E/flutter ( 5805): 	at com.android.internal.telephony.TelephonyPermissions.reportAccessDeniedToReadIdentifiers(TelephonyPermissions.java:381)
E/flutter ( 5805): 	at com.android.internal.telephony.TelephonyPermissions.checkPrivilegedReadPermissionOrCarrierPrivilegePermission(TelephonyPermissions.java:323)
E/flutter ( 5805): 	at com.android.internal.telephony.TelephonyPermissions.checkCallingOrSelfReadDeviceIdentifiers(TelephonyPermissions.java:257)
E/flutter ( 5805): 	at com.android.internal.telephony.TelephonyPermissions.checkCallingOrSelfReadDeviceIdentifiers(TelephonyPermissions.java:233)
E/flutter ( 5805): 	at com.android.server.os.DeviceIdentifiersPolicyService$DeviceIdentifiersPolicy.getSerialForPackage(DeviceIdentifiersPolicyService.java:68)
E/flutter ( 5805): 
E/flutter ( 5805): )
E/flutter ( 5805): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter ( 5805): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter ( 5805): <asynchronous suspension>
E/flutter ( 5805): #2      FlutterDeviceIdentifier.serialCode (package:flutter_device_identifier/flutter_device_identifier.dart:21:27)
E/flutter ( 5805): <asynchronous suspension>
E/flutter ( 5805): #3      _MyAppState.initPlatformState (package:newlauncherdequech/main.dart:50:17)
E/flutter ( 5805): <asynchronous suspension>
E/flutter ( 5805): 
`

**Comment by igormenin** [comment]
In Android 6.0 working.

**Comment by Joseph-Nathan** [comment]
any news ?

**Comment by arazi2021** [comment]
> `E/flutter ( 5805): Caused by: android.os.RemoteException: Remote stack trace: E/flutter ( 5805): at com.android.internal.telephony.TelephonyPermissions.reportAccessDeniedToReadIdentifiers(TelephonyPermissions.java:381) E/flutter ( 5805): at com.android.internal.telephony.TelephonyPermissions.checkPrivilegedReadPermissionOrCarrierPrivilegePermission(TelephonyPermissions.java:323) E/flutter ( 5805): at com.android.internal.telephony.TelephonyPermissions.checkCallingOrSelfReadDeviceIdentifiers(TelephonyPermissions.java:257) E/flutter ( 5805): at com.android.internal.telephony.TelephonyPermissions.checkCallingOrSelfReadDeviceIdentifiers(TelephonyPermissions.java:233) E/flutter ( 5805): at com.android.server.os.DeviceIdentifiersPolicyService$DeviceIdentifiersPolicy.getSerialForPackage(DeviceIdentifiersPolicyService.java:68) E/flutter ( 5805): E/flutter ( 5805): ) E/flutter ( 5805): #0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7) E/flutter ( 5805): #1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18) E/flutter ( 5805): <asynchronous suspension> E/flutter ( 5805): #2 FlutterDeviceIdentifier.serialCode (package:flutter_device_identifier/flutter_device_identifier.dart:21:27) E/flutter ( 5805): <asynchronous suspension> E/flutter ( 5805): #3 _MyAppState.initPlatformState (package:newlauncherdequech/main.dart:50:17) E/flutter ( 5805): <asynchronous suspension> E/flutter ( 5805): `

same in Android 13... no return value... '--"
